name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sh ./configure
    - name: build
      run: sh ./build
    - uses: actions/upload-artifact@v4
      with:
        name: UnlimitedLife-Linux-Ubuntu
        path: CBuild/

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: git mingw-w64-ucrt-x86_64-gcc
      
    - name: CI-Build
      run: |
        echo 'Msys2 build!'
        ./build.cmd
      
#    - name: Upload Windows Artifact
#      uses: actions/upload-artifact@v4
#      with:
#        name: UnlimitedLife-Windows
#        path: CBuild/
