name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sh ./scripts/configure
    - name: build
      run: sh ./scripts/build
    - name: RunningTests
      run: cd CBuild_CACHE/ ; ctest
    - uses: actions/upload-artifact@v4
      with:
        name: UnlimitedLife-Linux-Ubuntu
        path: CBuild/

  build-windows:
    runs-on: windows-latest
    env:
      MSYS2_PATH_TYPE: inherit
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        #install: git mingw-w64-ucrt-x86_64-gcc
        path-type: inherit  # 关键修复：继承环境变量
      
    - name: CI-Build
      shell: msys2 {0}  # 显式指定shell
      run: |
        sh ./scripts/configure_win_msys2.sh
        sh ./scripts/build_win_msys2.sh
        cp /ucrt64/bin/libgcc_s_seh-1.dll CBuild/
        cp /ucrt64/bin/libstdc++-6.dll CBuild/
    
    - name: RunningTests
      run: cd CBuild_CACHE_WIN/ ; ctest
      
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UnlimitedLife-Windows
        path: CBuild/
