name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure & build
      run: ./configure
    - uses: actions/upload-artifact@v4
      with:
        name: UnlimitedLife-Linux-Ubuntu
        # A file, directory or wildcard pattern that describes what to upload
        # Required.
        path: CBuild/Data