name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure & build
      run: ./configure
    - uses: actions/upload-artifact@v4
      with:
        name: UnlimitedLife-Linux-Ubuntu
        # A file, directory or wildcard pattern that describes what to upload
        # Required.
        path: CBuild/Data
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
      - uses: actions/checkout@v4
      - name: configure & build
        run: ./configure.bat
      - uses: actions/upload-artifact@v4
        with:
          name: UnlimitedLife-Windows
          path: CBuild/Data