name: Deploy to ULDoc

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须的写入权限

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # 关键权限保持

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Generate Docs
      run: |
        doxygen Doxyfile
        mkdir -p public/ULDoc
        cp -R Doxygen/* public/ULDoc/
        find public/ULDoc -name '*.html' -exec sed -i 's#<head>#<head><base href="/ULDoc/">#g' {} \;

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true  # 强制清空历史
        keep_files: false